### ISSUE TITLE
Cassandra Definitions

### ISSUE THREAD

**Issue by bruciebruce** [ANierbeck/BusFloatingData#11]
Hello,

Super cool project!

I downloaded your project but upon running I get what appears to be Cassandra exceptions because these keyspaces/tables have not been defined.  Do you have a script I can run against CQL to create the Cassandra constructs that your program expects, or do I infer that from the sql statements that I see in your code?

Thank you.

**Comment by ANierbeck** [comment]
It's here https://github.com/ANierbeck/BusFloatingData/blob/master/commons/src/main/resources/create_tables.cql

Thanks that you like it.

**Comment by bruciebruce** [comment]
Thanks.  Got it.
