### ISSUE TITLE
"aws_stack_id" in x_user_data.yml

### ISSUE THREAD

**Issue by nutzhub** [ANierbeck/BusFloatingData#12]
Hi, First of all thanks for awesome work. I'm trying to spin up DCOS on aws and use your work as baseline. So I look through and wonder about `coreos` cloud config 
```
"aws_stack_id": |-
        arn:aws:cloudformation:${aws_region}:097247269408:stack/${stack_name}/e16b6850-42a1-11e7-aec4-50a68a770c82
```
What is it related to and this is not cloudformation stack and seem to be hardcoded isn't it?

**Comment by ANierbeck** [comment]
it retrieves it's information from the variables, this way it's possible to start different stacks in different regions.
